### ISSUE TITLE
Responsive width

### ISSUE THREAD

**Issue by rlavoie** [qrohlf/trianglify#43]
What is the easiest way to have this scale full screen and update on resize

**Comment by qrohlf** [comment]
You will want to have some CSS to make the pattern scale, and some Javascript to regenerate the pattern regenerate when the resize is complete.

Here is how I'm doing it for https://qrohlf.com/trianglify: [CSS](https://github.com/qrohlf/trianglify/blob/gh-pages-src/css/style.scss#L137-L143) [JS](https://github.com/qrohlf/trianglify/blob/gh-pages-src/js/components/Hero.jsx#L32-L33)

**Comment by eliawk** [comment]
Can i reload trianglify without React?

**Comment by qrohlf** [comment]
Yes. Just hook into the window resize event and re render Trianglify onto the same canvas with the new size attributes.

**Comment by yaochiqkl** [comment]
Thankyou~ Like it very much. :smile: 
If I translate "Readme.md" in Chinese and create a "readme-cn.md" ,will you approve my pull request?

**Comment by qrohlf** [comment]
It's awesome that you want to contribute to the project! Thanks!

However, since I do not speak Chinese, it will not be possible for me to keep a Chinese-language Readme up-to-date. Without an experienced bilingual co-maintainer, I'm afraid I can't accept PRs that add new documentation in any languages that I don't speak.

Sorry!
