### ISSUE TITLE
Is there a way to update settings on an object?

### ISSUE THREAD

**Issue by TheInitializer** [qrohlf/trianglify#44]
I want to change the cell_size property dynamically and redraw the canvas but don't want to regenerate as that will create a completely different design... is that possible?

In the demos on your site you seem to have called a setState function but I don't seem to have that...

**Comment by TheInitializer** [comment]
Nevermind, I found the gh-pages-src branch. I'll probably be able to figure it out from there.

**Comment by qrohlf** [comment]
You may find the [seed](https://github.com/qrohlf/trianglify#seed) option useful - however, changing the cell size will result in a different number of points being added to the matrix and therefore a different design.

If what you want to achieve is a zoom functionality, you would be better served using some other technique rather than re-running the (computationally expensive) delauney triangulation algorithm for each redraw. The polygon coloring and geometry that trianglify uses to render is exposed in the pattern object that calls to Trianglify() return.

**Comment by TheInitializer** [comment]
Thanks, that's just what I needed. :)
