### ISSUE TITLE
Triangles overlap?

### ISSUE THREAD

**Issue by pwichmann** [qrohlf/trianglify#76]
First of all, thank you for a truly amazing library!

I found that in my results the corners of the triangles overlap. Is there a way to prevent that from happening?

![image](https://user-images.githubusercontent.com/13521375/27752763-96eccbb2-5dda-11e7-9d34-fc6fb9e5c51d.png)

**Comment by qrohlf** [comment]
Try either decreasing the [stroke_width](https://github.com/qrohlf/trianglify#stroke_width) value, or increasing your canvas size and cell size. The default stroke width is set up for display at typical screen resolution, and overdraws in order to prevent antialiasing artifacts that occur with coincident lines in SVG.

**Comment by pwichmann** [comment]
Lightning fast reaction, many thanks!

My canvas size is small:
* width: 300
* height: 200

I have now set the parameters to:
stroke_width: 1.1
cell_size: value between 20 and 80

Does that sound reasonable? Is there any rule of thumb I could apply to sanity check my settings?

Many thanks!

**Comment by qrohlf** [comment]
That seems reasonable. In order to have truly zero overlap between triangle
vertices you would need to set the stroke width to zero, but this may lead
to antialiasing artifacts. The best way to find out is to experiment, since
the severity of these artifacts will depend on your color scheme and
rendering method.
