### ISSUE TITLE
Anyway to do this with transparency levels?

### ISSUE THREAD

**Issue by Philiphlop** [qrohlf/trianglify#88]
I love trianglify.io, thank you for creating this. 

I do like to change the base colour for different scenarios, at the moment I am using SVG groups, but it is more management of sizes and positions than it could be. 

Is it possible to generate an SVG with different white transparency levels? 
Then apply a base colour underneath for a similar effect. 
The base colour can then be more easily changed without having to alter the SVG. 

Is this possible?

**Comment by qrohlf** [comment]
yes, but I need to change the color generation code here to use `.css()` instead of `.hex()` in order to support alpha attributes. You're welcome to submit a PR, but I probably won't have time to do a release until later in the week.

https://github.com/qrohlf/trianglify/blob/c8a9e880da41827df8f15526282944a77a3f6161/lib/trianglify.js#L114

**Comment by qrohlf** [comment]
@Philiphlop `v2.0.0` is now out with support for custom transparency levels in the output when you're generating SVGs. Clone the repo and open `examples/transparency-example.html` to see this in action.
